services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
  monitor:
    image: grafana/grafana-oss:latest
    container_name: monitor
    restart: always
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always